### ISSUE TITLE
Measuring test coverage

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#124]
Looking for a way for our test coverage to measured and fed back into GitHub as a status (just like build status in the readme.md). 

Test coverage should stay flat or increase, we will start rejecting pull requests that cause code coverage to decrease.

**Comment by mikedamay** [comment]
The following is orthogonal to your point about test coverage but this is a good place to raise my point and it may effect the tooling.

I don't see a huge amount of scope for unit testing (as opposed to integration and automated functional testing).  The business logic is fairly "thin" and large parts of the app are "forms over data".  I would propose that integration and functional testing are seen as of equal value with unit testing and the appropriate style should be selected depending on circumstances.  I understand if such a heterodox view and the threat of something like Selenium might be seen as off putting to potential contributors so I am happy to discuss.

**Comment by mikedamay** [comment]
DasBlog.SmokeTest is in branch test/smoke-test-2 in my fork. I know we don’t have a burning requirement for a smoke test but it is an excellent POC for Selenium.

I’m not trying to railroad the project into a particular technology with a fait accompli. I think much of the code and many of the lessons learnt in producing this can be used whatever we select.

Having said that there seem to be slim pickings when it comes to test automation if
https://dzone.com/articles/10-best-open-source-test-automation-frameworks-for is anything to go by. The most applicable ones seem to be based on Selenium anyway.

Please have a look at:
https://github.com/mikedamay/dasblog-core/blob/test/smoke-test/source/SeleniumPlusDasBlogCoreInACoupleOfPages.md

and

https://github.com/mikedamay/dasblog-core/blob/test/smoke-test/source/DasBlog.SmokeTest/readme.md

In Selenium’s favour it is compatible with Xunit and I have successfully run DasBlog.FunctionalTests on the github AppVeyor connection.

I have only added a couple tests to the smoke test at present. One consequence of my approach is to lean heavily on HTML element ids in order to keep the need for our collective understanding of Selenium to a minimum. I therefore want to avoid finding myself with a bunch of nasty merging to do.

I should welcome any editorial comment you have on the 2 documents above. The thing about code is that it may be disappointing if your colleagues don’t understand it but at least you have the consolation that the machine does. With published documentation if it doesn’t speak to other people then you are pretty much wasting your time.

**Comment by mikedamay** [comment]
A note of this - just in case it loses its no. 1 ranking on Google
https://github.com/tonerdo/coverlet?WT.mc_id=-blog-scottha
