### ISSUE TITLE
Captcha when commenting

### ISSUE THREAD

**Issue by peteringemann** [poppastring/dasblog-core#363]
implement captcha test whenever someone wants to add comments

**Comment by thousandtyone** [comment]
Is anyone already working on this? If not, I would be happy to take this up and give this a shot.

**Comment by poppastring** [comment]
Hey @thousandtyone, Help on this issue is most welcome!

Please note that there is a `EnableCaptcha` (true/false) setting that should enable and disable this option.

I am not sure how useful this is but there is prior art in the original dasblog code here: https://github.com/shanselman/dasblog/tree/master/source/WebControlCaptcha

I am very interested to see what you come up with.

Thanks!

**Comment by thousandtyone** [comment]
Thanks! Will start working on this and send a Merge Request / Pull Request
when done.

**Comment by thousandtyone** [comment]
Uploading a PR soon so thought I might document the changes done. 

- We are not in the business of building Captcha so instead I focused on integrating with Google Recaptcha. We still honour and use the Enable Captcha Setting to decide if we want to show the captcha or not.

- To start using the captha you just go to google website and register for the captcha there. 

![recaptchagooglesettings](https://user-images.githubusercontent.com/24845706/91662406-d5a2d580-eaff-11ea-9755-5f977fd8068b.jpg)

- Once you do the following you get something called **Site Key and Secret Key** from Google. They are pretty easy to spot.

- Once you have them you come to DasBlog settings. You enable your captcha and you enter those two values in the right place in the settigns screen.

![recaptchasettingsdasblog](https://user-images.githubusercontent.com/24845706/91662433-01be5680-eb00-11ea-850e-612034043401.jpg)

- Oh, and the score is something that decides how 'strict' your captcha is. Generally the captcha is pretty smart and won't even ask for images. It tracks using the users trend. But if it does ask you for images, the mimimum score decides how strict the captcha is. So for example if it shows you images and asks you to pick dogs, you have to pick 70% right dogs if the minimum score is 0.7 for the captcha to consider you a human being.

- Also, don't forget to empty out cheesy question and answer text boxes to disable that if you are using captcha. You can use both of them, but using both of them makes it a pain for the user to fill comments. Personally I highly recommend you disable this if you are using the recaptcha.

- Also, failing to enter captcha correctly, does not currently show any errors but it doesn't let you comment. This is **exactly** how Cheesy question and answer also work. It seems like a pattern across the codebase. I'll file that as a seperate issue. Happy to help with fixing that if needed.

- You have to restart dasblog once for the captcha to work since the site key and secrets are loaded using dasblog bootup. So after you have made the changes to configuration don't forget to restart dasblog.

- At  this point if you've done everything correctly you should have a working recaptcha on comments:
![recaptcha](https://user-images.githubusercontent.com/24845706/91662713-d3da1180-eb01-11ea-9f47-57c832472ebc.jpg)

- And when you try to post it should also work:
![recaptchaworking](https://user-images.githubusercontent.com/24845706/91662783-392e0280-eb02-11ea-8239-f40d4581390e.jpg)

- Note the Google is pretty smart at finding out if  you are a valid user so the captcha may not always ask you for proof or make you pick images. That's fine. If you want to still test by seeing images you can create a new user agent using chrome developer tools to test. Here is a link that provides more details: https://www.tectite.com/fmhowto/test-invisible-recaptcha.php?WWWTECTITE=p32j2na5otc4rmtbmfsmf9rci6

- Realistically this should be simple to setup. The steps are simply: 1. Register For a re-captcha in Google. 2. Turn on Enable Captcha setting. 2. Patch in the keys in Dasblog. 3. Restart DasBlog.

Happy to help if there are any issues with the PR or anyone needs any added help with this. If People want to use invisible captcha  or captcha 3 happy to provide support for that as well, but right now this is what most people seem to be using so build the default setup only for that. Please feel free to reach out to me or let me know if any added help is required. Will be submitting the PR in the next hour or so.

**Comment by thousandtyone** [comment]
Uploading a PR soon so thought I might document the changes done. 

- We are not in the business of building Captcha so instead I focused on integrating with Google Recaptcha. We still honour and use the Enable Captcha Setting to decide if we want to show the captcha or not.

- To start using the captha you just go to google website and register for the captcha there. 

![recaptchagooglesettings](https://user-images.githubusercontent.com/24845706/91662406-d5a2d580-eaff-11ea-9755-5f977fd8068b.jpg)

- Once you do the following you get something called **Site Key and Secret Key** from Google. They are pretty easy to spot.

- Once you have them you come to DasBlog settings. You enable your captcha and you enter those two values in the right place in the settigns screen.

![recaptchasettingsdasblog](https://user-images.githubusercontent.com/24845706/91662433-01be5680-eb00-11ea-850e-612034043401.jpg)

- Oh, and the score is something that decides how 'strict' your captcha is. Generally the captcha is pretty smart and won't even ask for images. It tracks using the users trend. But if it does ask you for images, the mimimum score decides how strict the captcha is. So for example if it shows you images and asks you to pick dogs, you have to pick 70% right dogs if the minimum score is 0.7 for the captcha to consider you a human being.

- Also, don't forget to empty out cheesy question and answer text boxes to disable that if you are using captcha. You can use both of them, but using both of them makes it a pain for the user to fill comments. Personally I highly recommend you disable this if you are using the recaptcha.

- Also, failing to enter captcha correctly, does not currently show any errors but it doesn't let you comment. This is **exactly** how Cheesy question and answer also work. It seems like a pattern across the codebase. I'll file that as a seperate issue. Happy to help with fixing that if needed.

- You have to restart dasblog once for the captcha to work since the site key and secrets are loaded using dasblog bootup. So after you have made the changes to configuration don't forget to restart dasblog.

- At  this point if you've done everything correctly you should have a working recaptcha on comments:
![recaptcha](https://user-images.githubusercontent.com/24845706/91662713-d3da1180-eb01-11ea-9f47-57c832472ebc.jpg)

- And when you try to post it should also work:
![recaptchaworking](https://user-images.githubusercontent.com/24845706/91662783-392e0280-eb02-11ea-8239-f40d4581390e.jpg)

- Note the Google is pretty smart at finding out if  you are a valid user so the captcha may not always ask you for proof or make you pick images. That's fine. If you want to still test by seeing images you can create a new user agent using chrome developer tools to test. Here is a link that provides more details: https://www.tectite.com/fmhowto/test-invisible-recaptcha.php?WWWTECTITE=p32j2na5otc4rmtbmfsmf9rci6

- Realistically this should be simple to setup. The steps are simply: 1. Register For a re-captcha in Google. 2. Turn on Enable Captcha setting. 2. Patch in the keys in Dasblog. 3. Restart DasBlog.

Happy to help if there are any issues with the PR or anyone needs any added help with this. If People want to use invisible captcha  or captcha 3 happy to provide support for that as well, but right now this is what most people seem to be using so build the default setup only for that. Please feel free to reach out to me or let me know if any added help is required. Will be submitting the PR in the next hour or so.

**Comment by thousandtyone** [comment]
PR Added: https://github.com/poppastring/dasblog-core/pull/457
Had to file a couple of them because there were some conflicts since I started working on this. Wanted to resolve them and submit a clean PR. Please feel free to close this one.
