### ISSUE TITLE
cancel Comment Section

### ISSUE THREAD

**Issue by peteringemann** [poppastring/dasblog-core#366]
If you start writing a comment you can't really get rid of the comment section if you wanna go back and just discard it. Even if you start navigate older posts and then go back to the page that holds the post you're commenting, the comment section is still open.

In fact it's pretty difficult to get rid of the Comment Section. Not even Ctrl+R or Ctrl+F5 or closing the page tab or entire browser will get rid of the Comment Section. You have to delete the post to discard the Comment Section.

It would be nice if there was a cancel button.

**Comment by dsmeltz** [comment]
Try setting the ShowItemSummaryInAggregatedViews in site.config to true.  This will use the *Summary parts of the themes.  The only theme that sort-of works with this setting, is median.  The others are including the Comment partial on the BlogItemSummary partial, which is why the comments are showing all the time, regardless of the ShowItemSummaryInAggregatedViews setting.  

When using the median theme, If you click the big purple button with the post title in it, you'll go to the _BlogPage view and you're comments will be displayed.  You can also enter a new comment.

**Comment by poppastring** [comment]
@dsmeltz Thanks for the feedback here, I will copy this and create a new issue and investigate .
