### ISSUE TITLE
Try setting the ShowItemSummaryInAggregatedViews in site.config to true

### ISSUE THREAD

**Issue by mklump** [poppastring/dasblog-core#442]
Try setting the ShowItemSummaryInAggregatedViews in site.config to true.  This will use the *Summary parts of the themes.  The only theme that sort-of works with this setting, is median.  The others are including the Comment partial on the BlogItemSummary partial, which is why the comments are showing all the time, regardless of the ShowItemSummaryInAggregatedViews setting.  

When using the median theme, If you click the big purple button with the post title in it, you'll go to the _BlogPage view and you're comments will be displayed.  You can also enter a new comment.

_Originally posted by @dsmeltz in https://github.com/poppastring/dasblog-core/issues/366#issuecomment-605493911_

I am also trying to make work through testing the median pre-built theme using the wiki docs here for deployment and designing a theme. After all that, the search button in this theme does not work and clicking on category and then a daily post item does not work. I am a nube attempting to work on this mediam theme with the introductions given, but it seems some major configuration is missing. Kindly what is missing?

**Comment by mklump** [comment]
Thank you for attempting to provide that setting the flag for config ShowItemSummaryInAggregatedViews will fix everything.
I believe a different developer for a much older Dasblog v2.13 approximately said the same thing to take care of all our troubles.
Bucko that won't do here having tested that one *again*.
1) Category then Item view issue is a persistent problem across every Theme - reproduces 100%
2) The search box given with the Median Theme will still never function no matter what URL location you set your blog to in Config. The postpack after clicking Search button appears to be trying to submit back to an ASP.NET view page that does not exist - 100% broken search reproduces 100% of the time. The _Layout.cshtml line of code 'form action="/post/search" method="post"' for that form postback goes to nothing!
Now what or does this also stay unfixed?

**Comment by poppastring** [comment]
@mklump  Thanks for the feedback. It will probably be it a bit easier if we have one bug per issue. It sounds like we also have category issue and a search issue? Let's create separate issues for those with enough details for me to replicate those problems.

Lets start discussing the "ShowItemSummaryInAggregatedViews" issue here. This config allows you to create an alternate theme for your front page (you can have cards representing each post or whatever really). It sounds like you were anticipating that I create alternate summary styles for each theme. I did not, but your suggestion makes sense to me. It gives everyone more examples to work with as they create their own themes. However, aside from that it does appear to be working as designed (even if I did not create differing summary style).

My task seems to be to start creating "summary" versions for all themes so that by default all themes respond when you select "ShowItemSummaryInAggregatedViews".

Have I missed anything? Was there any other problems directly related to "ShowItemSummaryInAggregatedViews".

**Comment by poppastring** [comment]
@mklump My most recent changes should address the Summary Items configuration for all the default themes (need changes in _BlogItemSummary.cshtml and _BlogPageSummary.cshtml). 

The overall assumption here is that if you want to permanently modify a theme you should create a new one under the **Themes** folder (say Median2). You can select that theme by logging in and updating the themes in the **Site Admin** page.

I hope this helps you get going on "ShowItemSummaryInAggregatedViews" issue. I will keep this issue open for a few days to address further concerns or inquires on this topic and open new issues for the "Category" and "Search" issues/discussion.

**Comment by mklump** [comment]
Greetings again to you  <mailto:reply@reply.github.com> @poppastring/dasblog-core[friend Mark Downie]:

 

In this reply, I will try to again provide more details on the second issue that was found in my last write up regarding the ../blog_path/post/search view 404 not found...

For this second noted 404 error, I had the following initial conditions,

*	After having followed your build and deploy wiki guidance [https://github.com/poppastring/dasblog-core/wiki/1.-Deployment] with the Microsoft pages, I have the following buildout directory structure that should appear the same or near the same as yours in the following small .JPG:

*	

*	Per your suggestion, I did attempt to start new changes with a brand new theme named “Median2” per the wiki guidance found at [https://github.com/poppastring/dasblog-core/wiki/4.-Designing-a-theme] of which resulted in –

*	C:\WINDOWS\system32>cd "C:\inetpub\wwwroot\blog_new"
*	 
*	C:\inetpub\wwwroot\blog_new>dir /a .\dasblog-core.exe
*	Volume in drive C is Windows
*	Volume Serial Number is 8E87-9353
*	 
*	Directory of C:\inetpub\wwwroot\blog_new
*	 
*	07/16/2020  12:51 AM           174,592 dasblog-core.exe
*	               1 File(s)        174,592 bytes
*	               0 Dir(s)  287,318,024,192 bytes free
*	 
*	C:\inetpub\wwwroot\blog_new>.\dasblog-core.exe newtheme "Median2"
*	Could not execute because the specified command or file was not found.
*	Possible reasons for this include:
*	  * You misspelled a built-in dotnet command.
*	  * You intended to execute a .NET Core program, but dotnet-newtheme does not exist.
*	  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
*	 
*	C:\inetpub\wwwroot\blog_new>dasblog-core --help
*	.NET Core SDK (3.1.302)
*	Usage: dotnet [runtime-options] [path-to-application] [arguments]
*	 
*	Execute a .NET Core application...blah...blah

*	The last error specified command or file not found from the output of command dasblog-core newtheme “my_next_theme” most likely lacks either additional path configuration or another coded binary or compiled assembly library is seriously lacking? Either way as a result of that last error “Not found” I gave up and went back to trying to run the original “median” pre-provided theme pack to see if I can get that working, and it did to a point...
*	The next action I took was seeing that the code given for “median” theme does provide the following code for a search box field as –

*	
*	    <div class="input-group">
*	        <form action="/post/search" method="post">
*	            <input id="searchText" name="searchText" type="text" class="form-control input-md" placeholder="Ask a question..." />
*	            <span class="input-group-btn">
*	                <button class="btn btn-primary btn-md" id="btn-todo" type="submit">Search</button>
*	            </span>
*	        </form>
*	    </div>

*	I see that in this code from ../blog_path/Themes/median/_Layout.cshtml did render this searchText box and submit button.
*	I then attempted to use this searchText box with the text “Nant” of known existing text first at http://localhost/blog_new test path, and then again at my production site http://www.[my_production_site].com/blog.

*	The form submit routed to [http://localhost/post/search], and seeing that the path ../blog_new/Views/post/Search/ test path did not exist, this produced a 404 error -
*	HTTP Error 404.0 - Not Found
*	The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

*	I again attempted to use this searchText box with the text “Nant” of known existing text for the second time at http://www.[my_production_site].com/blog -

*	The form submit routed to [http://www.[my_production_site].com/post/search], and seeing that the path ../blog/Views/post/Search/ production path did not exist, this produced a different error –


o  HTTP Error 500.0 - Internal Server Error


o   Internal Server Error


*	Detailed Error Information:
*	Module       ManagedPipelineHandler
*	Notification      ExecuteRequestHandler
*	Handler      ExtensionlessUrlHandler-Integrated-4.0
*	Error Code        0x800703e9
*	Requested URL     http://www.[my_production_site].com:80/post/search
*	Physical Path     [my_physical_server_share_path]\post\search
*	Logon Method      Anonymous
*	Logon User        Anonymous

*	All help is greatly appreciated, and I will post this general information without my site PII info...

 

-Matthew James K.

http://www.klump-pdx.com

**Comment by poppastring** [comment]
@mklump 

If I can summarize:

- The main page renders correctly and shows a list of posts.
- The **ShowItemSummaryInAggregatedViews** does correctly change the view of the main page (this was not the case before).
- The category section renders correctly with a list of posts by category.
- Clicking on any individual post results in a 404.
- Regardless of the value of **ShowItemSummaryInAggregatedViews** we get 404s for individual posts.


This feels like a setup issue ([IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-3.1&tabs=visual-studio), or something else) rather than a DasBlog-Core  but lets go through this systematically. 


Would it be possible to test this without IIS? Using Kestrel from the command line? This would confirm whether the issue is with IIS or with DasBlog-Core specifically (to be sure, I will try to help either way).

I have just run the following steps locally to host with Kestrel at the command line (not IIS), please try this:

- In Visual Studio click the **Build** menu and select **Publish->DasBlog.Web** (select the Folder you want to publish to).
- From the command line navigate to your Publish folder
- This folder should could contain **Dasblog.Web.exe** and **dasBlog-core.exe**
- Execute the following to set the site root element to localhost : **dasblog-core config root https://localhost:5001**
- Execute the following start up dasblog-core: **Dasblog.Web.exe**
- In the browser navigate to **https://localhost:5001**
- The site should be up and running with the default theme (darkly I think).
- You can also change the theme to _dasblog_ (or something else) from the CLI using this:  **dasblog-core config theme dasblog**
- Refresh the browser the site to see the new theme applied.

I know this does not answer all your questions yet but if we cannot get this far we know we have a  problem with the environment or IIS.

If this works we should look at [IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-3.1&tabs=visual-studio) next.

**Comment by poppastring** [comment]
Ok I just visited your site and I think I understand the bug now. 

You are currently configured to **Enable unique URls** in the site admin page. Which means each page should be prefixed with the date as in **blog/2020/07/08/some-blog-post**.

On the category page it does not honor this format and attempts to go directly to **blog/some-blog-post**.  This is also the case in the RSS feed. 

I will start working on this immediately. Thanks for you persistence and patience!!!

**Comment by poppastring** [comment]
Hi @mklump 

I believe the latest PR resolves the issue where links on the Category pages (and RSS feed) were not working when you enable **Enable unique URls** . You will need to pull down the latest changes and deploy. I will start working on the next issue. Thx!
