### ISSUE TITLE
Deploy to Azure button

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#492]
Need a solution for easy deployment to Azure for anyone who wants to use dasblog-core. Currently the only options are to xcopy the content of the zip file or use Visual Studio.

I was assuming something [this would be one option](https://devblogs.microsoft.com/cse/2017/01/17/the-deploy-to-azure-button/).

**Comment by bradwyoung** [comment]
I am hosting on Azure.  I am using a GitHub action to deploy.  I would be happy to bounce some ideas around.

**Comment by poppastring** [comment]
@bradwyoung I updated the description. Definitely open to any ideas or suggestions, just want it to be a simply deployment process.

**Comment by rumdood** [comment]
What sort of deployment setup would be the end-goal here? There's [some documentation from MSFT](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button) on how to create a Deploy to Azure button using ARM templates. There is a template for a deployment that links the App Service to a GitHub Repo and the branch of the deployer's choice (pictured here using the baseline MSFT quickstart template):

![image](https://user-images.githubusercontent.com/3585996/140018866-010d04ac-defc-4a90-8298-2c5099ee7b63.png)

More about that template [here](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.web/web-app-github-deploy). There would probably still need to be some instructions needed if you wanted to prevent a user from linking their site to the main repo's master branch instead of their own fork.

The ARM templates are obviously a pretty deep rabbit hole to fall into, so I'd be curious as to which things should be setup (custom domain/certificates/deployment slots/etc).

**Comment by poppastring** [comment]
hey @rumdood,

Thanks for this input! I would be absolutely fine with the approach you noted above, and that the user could optionally select their own fork. Could we provide prescriptive instructions for the domain and cert steps? It it even possible to template that?

I am respectively using [Ghost ](https://ghost.org/docs/install/) as the North Star for ease of installation. They have a an easy to follow story for installing to:
- Cloud (I want us to focus on Azure, [the current instructions are not straightforward](https://github.com/poppastring/dasblog-core/wiki/1.-Deployment))
- Local (just a few dotnet CLI commands)
- Docker (regular builds to docker)
- Install from Source (part of the Visual Studio deploy)

[p.s. I will create issues for these additional scenarios :)]

**Comment by rumdood** [comment]
I think we can put together a template pretty easily. The MSFT templates include ones for certs, custom domain names, etc. I can try to pull them all together in a single template. I'll draft something up and post a PR for review.

**Comment by rumdood** [comment]
Just a note that I haven't disappeared. I had a mostly working template, but the Net6 update seems to be causing issues when I try to run dasblog-core init post-deploy. Not sure what that's about.

Once I have that solved I think we can make this pretty easy for a user. Give them a button to click that will allow them to configure some basic stuff and once they tell Azure to go, it can create the resources, pull the code from the repo, and build and init the site.

There would still need to be instructions on certificates/custom domains, but I think with custom deploy shell scripts we can make it pretty close to point and click to start the site up with an azurewebsites.net URL.

**Comment by rumdood** [comment]
For the ARM template for this, do you prefer the site default to 32-bit or 64-bit? I'm trying to make sure I hit all the appropriate defaults.

Right now I have a template that does:

- .NET 6
- Windows
- Pricing Tier B1

By the end of this weekend I hope to have it able to also set the production env variable and at least run the ```dasblog-core.exe init```.

**Comment by poppastring** [comment]
@rumdood Let's go for 64 bit.

These defaults look great. Many thanks!

**Comment by rumdood** [comment]
OK, sorry for falling off of the planet for nearly two months, but circling back around to this, I don't know that using a post-deploy script makes much sense. The script is really two commands - the init and the config. The init could be performed in a post-deploy script assuming the init is idempotent or we can add a check for the correct config files based on environment variables, etc.

The config command is harder to script because it is expecting the full public URL of the site unless I'm mistaken. So if the user is setting up a custom domain instead of using the assigned azurewebsites URL, the script would have to require the user deploying the site to know the final URL they're looking to use before deploying the ARM template. 

I took a look at the Ghost deployment instructions for things like Digital Ocean and they still have some manual shell commands, so it may be that the best path forward is to forgo the post-deploy script for now.

**Comment by poppastring** [comment]
@rumdood Delays are part of the process, no worries!

I am totally fine with your suggestions, anything that will reduce complexity will be welcom. Thx!

**Comment by rumdood** [comment]
OK, last question (I think).

ARM template is done. The Deploy To Azure button is easy to embed in a markdown file - just need to know which one, and I'm thinking it should involve some updated documentation in the Wiki, which of course is a separate repo and will need it's own PR(s).

So my proposal would be a multiple PR process akin to this:

1. PR1 deploys the ARM template. Deploy To Azure button doesn't go anywhere yet because there are no instructions
2. PR2 is for the WIKI and adds a page or section specifically for using the DTA button and the DTA button itself
3. PR3 is an update to the README, adding the link to "one click deployment" or something along those lines. The DTA button could go on the README, but there would still need to be instructions available and I'm having trouble conceiving of what the process would look like with a DTA on one page and then you have to click to the instructions on another page.

I have the branch up on my fork with a possible bit of text for the README (note that the post-deployment instructions is a dummy link at the moment and the DTA button does work but the link would need to be modified to point to the ARM template in the root/main repo):

https://github.com/rumdood/dasblog-core/tree/issue-492-deploytoazurebutton

**Comment by poppastring** [comment]
@rumdood I am good with the rollout you are suggesting. This looks great!

**Comment by rumdood** [comment]
@poppastring - I have the updated instructions for the Wiki - but of course you can't fork wikis. Are you cool with me pushing a branch to your wiki repo?

**Comment by rumdood** [comment]
Well I appear to be unable to push a branch to the wiki site, so instead, since it's just one file, I've put a proposed updated to the [Deployment.md up as a gist](https://gist.github.com/rumdood/31ef2ec85ece9217c2d9958a5e52df63 )

**Comment by poppastring** [comment]
@rumdood Done! Awesome work, thank you!
