### ISSUE TITLE
Why is About and Contact views explictly returning NoContent

### ISSUE THREAD

**Issue by bradwyoung** [poppastring/dasblog-core#520]
Seems like if the view was returned, then copying the CSHTML to the theme folder would allow each of the view to be customized.  It is an easy change but I want to understand why it was implemented this way.

**Comment by poppastring** [comment]
@bradwyoung I love this idea! I think the only reason I returned a no content is because I was trying to figure out what to do with the default actions created in the original asp.net core project.

Please submit a PR with your ideas, my only suggestion would be to try an incorporate tag helpers (e.g. site-description, site-title, site-subtitle) in the CSHTML files so that folks can easily update the content of the default pages by using the Site Admin page.
